// RobotBuilder Version: 6.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;

import java.util.function.BooleanSupplier;
import java.util.function.DoubleSupplier;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import frc.robot.Constants;
import frc.robot.LimelightHelpers;
import frc.robot.TagApproaches;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.Swerve;
import frc.robot.subsystems.Vision;

/**
 *
 */
public class DriveToTag extends Command {
    private DoubleSupplier translationSuppier;
    private DoubleSupplier strafeSupplier;
    private DoubleSupplier rotationSupplier;
    private BooleanSupplier robotCentricSupplier;
    private NetworkTable limelightTable = NetworkTableInstance.getDefault().getTable("limelight-cybears");

    private double heldTargetXVector = 0.0;
    private double heldTargetYVector = 0.0;
    private boolean targetLock = false;


    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final Swerve m_swerve;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public DriveToTag(Swerve subsystem,
            DoubleSupplier translationsupplier,
            DoubleSupplier strafeSupplier,
            DoubleSupplier rotationSupplier,
            BooleanSupplier robotCentricSupplier) {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_swerve = subsystem;
        addRequirements(m_swerve);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        this.translationSuppier = translationsupplier;
        this.strafeSupplier = strafeSupplier;
        this.rotationSupplier = rotationSupplier;
        this.robotCentricSupplier = robotCentricSupplier;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }


    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        // Set values as if we are driving.
        /* get values, deadband */
        double translationValue = MathUtil.applyDeadband(translationSuppier.getAsDouble(), Constants.stickDeadband);
        double strafeValue = MathUtil.applyDeadband(strafeSupplier.getAsDouble(), Constants.stickDeadband);
        double rotationValue = MathUtil.applyDeadband(rotationSupplier.getAsDouble(), Constants.stickDeadband);

        // double joystickAngle = (strafeValue != 0) && (translationValue != 0)
        //         ? Math.toDegrees(Math.atan2(strafeValue, translationValue))
        //         : 0;
        // Based on where the joystick is held, this calculates the magnitude of the x and y coordinates.  
        // This is used when we take over stearing, but leave the driver in control of speed.
        double magnitude = Math.sqrt(Math.pow(translationValue, 2) +
            Math.pow(strafeValue, 2));

        double xTargetVector;
        double yTargetVector;
        double targetAngle;
        double targetRadians;


        // Get the id of the target we are heading for and lookup the offset for that target.   
        //   The offset should move the cross hairs for targeting so the robot arrives at an offset.
        //double targetOffset = getTargetOffset();

        // Get the  angle to the target
        targetAngle = targetAcquired() ? getTargetDegrees() - m_swerve.getHeading().getDegrees() : 0;
        targetRadians = Math.toRadians(targetAngle);
        xTargetVector = targetAcquired() ? magnitude * Math.cos(targetRadians) : 0;
        yTargetVector = targetAcquired() ? magnitude * Math.sin(targetRadians) : 0;

        SmartDashboard.putBoolean("driver/Target Lock", targetLock);
        double targetYScreenPos = LimelightHelpers.getTY("limelight-cybears");
        if (targetAcquired()){
            heldTargetXVector = xTargetVector;
            heldTargetYVector = yTargetVector;
            if (LimelightHelpers.getTY("limelight-cybears") > 12)
                targetLock = true;
        }

        // // See if we have a target and we are not in target lock state.
        if (!targetAcquired() && !targetLock) {
            m_swerve.drive(
                    new Translation2d(translationValue, strafeValue).times(Constants.Swerve.maxSpeed),
                    rotationValue * Constants.Swerve.maxAngularVelocity,
                    !robotCentricSupplier.getAsBoolean(),
                    true);
        } else {
            if (!targetAcquired() && targetLock == true){
                xTargetVector = heldTargetXVector;
                yTargetVector = heldTargetXVector;
            }
            double rotPower = targetYScreenPos > 6.8 ? Vision.getInstance().GetTargetRotPower() :
                Vision.getInstance().GetTargetTurnPower();
            m_swerve.drive(
                    new Translation2d(-xTargetVector, yTargetVector).times(Constants.Swerve.maxSpeed),
                    rotPower * Constants.Swerve.maxAngularVelocity,
                    !robotCentricSupplier.getAsBoolean(),
                    true);
        }
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }

    private boolean targetAcquired() {
        // Do we have a valid target from limelight?
        if (LimelightHelpers.getTV("limelight-cybears")){
            // Get the FiducialID of the target from limelight
            int id = (int) LimelightHelpers.getFiducialID("limelight-cybears");

            // Check that the id is valid for the game (1-16).   Sometimes misreads tags
            if (id > 0 && id <= 16) {
                // Determine your current alliance and compare it to the alliance of the tag we have targeted.
                Alliance myAlliance = DriverStation.getAlliance().get();
                return (TagApproaches.getInstance().TagAlliance(id) == myAlliance);
            }
        }
        // if all else fails, we don't have a target.
        return false;
    }

    private double getTargetDegrees() {
        return LimelightHelpers.getTX("limelight-cybears");
    }

    private double getTargetOffset() {
        int fidID;
        double offset = 0;
        // TODO Auto-generated method stub
        if (targetAcquired()){
            fidID = (int) LimelightHelpers.getFiducialID("limelight-cybears");
            if ((fidID >= 1) && (fidID <= 15)){
                offset = TagApproaches.getInstance().LimelightCrosshairOffset(fidID);
                
            }
        }
        return offset;
    }


}